recsys_predict:
  description: >
    user with description {user_profile} have {fan_count} followers. he/she post a rumor post {post} 
    created at {created_timestamp}, and current timestamp is {current_timestamp}. The rumor post is likely 
    to be recommend to recievers {candidates} by the recommendation system {rec_type}. Given recievers' 
    personal information, choose 0~{num} most possible recievers the post will be recommended to by predicting 
    the recommendation pattern:

    {recievers}

    You can resort to knowledge sources for more information about corresponding recommendation pattern.

  expected_output: >
    A list of user ids of the recievers the post will be recommended to.
  agent: recommend_predict_agent
