evaluate_candidate:
  description: >
    Given the personal information of posterA and some other recievers(user1, user2, ...), a post created by posterA 
    and the corrisponding recommendation pattern, predict most possible recievers the post will be recommended to.
    you can choose less than {num} recievers for the answer.

    The type of the recommendation pattern is {rec_type}.

    posterA's personal information and post:
    {
        "user_id": posterA_id,
        "user_profile": posterA_profile,
        "post": posterA_post,
    }

    recievers' personal information:
    [
      {
        "user_id": reciever_id_1,
        "user_profile": "reciever_profile_1",
      },
      {
        "user_id": reciever_id_1,
        "user_profile": "reciever_profile_1",
      },
      ...
    ]

    You can resort to knowledge sources for more information about corresponding recommendation pattern.

  expected_output: >
    A list of user ids of the recievers the post will be recommended to.
  agent: recommend_predict_agent
