rumor_identification:
  description: >
    user post: {post_content}. Identify whether the user believes in one of the given rumors: {rumor_sources}.
    Return "yes" or "no".

  expected_output: >
    "yes" or "no". Don't output anything else.
  agent: rumor_identifier_agent
