rumor_inoculation:
  description: >
    Now there is a rumer post on the social media that is factually wrong: {rumor}. It is now very likely to 
    spread to user with description {profile}, because user {reason_been_chosen}. To prevent this, we need to 
    generate a inoculation content to immunize the user against the rumor. you can choose several
    inoculation methods to generate the content:
    
    1. If you can just get people to think about accuracy, then they’re less likely to share bad content.
    2. By pre-emptively forewarning and exposing people to severely weakened doses of misinformation 
    (coupled with strong refutations), people can cultivate cognitive resistance against future misinformation

    you can use your knowledge in {topic} to inoculate the rumor.
    You can resort to knowledge sources for specific explaining of the methods.
    use a simple, natural and novel toungue so that everyone understand. Don't make it paragraphic.

  expected_output: >
    a text that inoculates the rumor.
  agent: rumor_inoculation_agent
