rumor_refute:
  description: >
    Now there is a rumer post on the social media that is factually wrong: {rumor}. user with description 
    {profile}, believes that the rumor is true and is now a target for rumor refutation, because user {reason_been_chosen}.
    Please write a post to inoculate user from the misinformation. Your post content should follow the following 
    format but more correlated with the rumor:
                    State the truth first: Lead with the fact if it’s clear, pithy, and sticky—make 
                    it simple, concrete,and plausible. Provide a factual alternative that fills a causal “gap”, 
                    explaining what happened if the misinformation is corrected. Do not rely on a simple 
                    retraction (“this claim is not true”).
                    Point to misinformation: Warn that a myth is coming. Repeat the misinformation, 
                    only once, directly prior to the correction.
                    Explain why misinformation is wrong: Explain how the myth misleads. Point out 
                    logical or argumentative fallacies underlying the misinformation.
                    State the truth again: Finish by reinforcing the fact. Repeat the fact multiple 
                    times if possible.

    use a simple, natural and novel toungue so that everyone understand.
    use your knowledge in {topic} to refute the rumor.
    You can resort to knowledge sources for the example of how to refute the rumor step by step.

  expected_output: >
    a text that refutes the rumor and clarifies the truth. Don't make it paragraphic.
  agent: rumor_refute_agent
