recsys_predict:
  description: >
    Evaluate a user's susceptibility to rumors online based on the provided personal profile
    and choose the {num} most susceptible user for the rumor clarification.

    Use your expertise in social psychology and focus on psychological factors that contribute to susceptibility and
    identify the most susceptible users.

    PERSONAL PROFILE:
    [
      {
        "user_id": user_id_1,
        "user_profile": "user_profile_1",
      },
      {
        "user_id": user_id_1,
        "user_profile": "user_profile_1",
      },
      ...
    ]
    
    for each user you choosed, your answer MUST include:
    - The selected user's ID(int)
    - A breif reasoning for your choice with less than 20 words

  expected_output: >
    A list of user IDs and a brief reasoning for each choice:
    [
      {
        "user_id": user_id_1,
        "reasoning": "reasoning for user_id_1"
      },
      {
        "user_id": user_id_2,
        "reasoning": "reasoning for user_id_2"
      },
      ...
    ]
  agent: suscept_test_agent
