suscept_evaluation:
  description: >
    Evaluate the given users' susceptibility to rumors based on the provided information.
    choose {num} most susceptible users from {candidates} and provide a reasoning for each choice.

    personal_profile:
    [
      {
        "user_id": id,
        "user_profile": "user_profile",
      },
      ...
    ]
    
    for each user you selected, your answer MUST include:
    - The selected user's id (int)
    - A brief reasoning for your choice with less than 20 words

  expected_output: >
    A list of user IDs and a brief reasoning for each choice:
    [
      {
        "user_id": selected id,
        "reason": "reasoning for choice"
      },
      ...
    ]
  agent: suscept_test_agent
